package org.zhangqh.core.classfile;

public enum Attribute_Tag {
    CONSTANT_VALUE, CODE, STACKMAPTABLE, EXCEPTIONS, INNERCLASSES, ENCLOSINGMETHOD, SYNTHETIC, SIGNATURE, SOURCEFILE, SOURCEDEBUGEXTENSION, LINENUMBERTABLE, LOCALVARIABLETABLE, LOCALVARIABLETYPETABLE, DEPRECATED, RUNTIMEVISIBLEANNOTATIONS, RUNTIMEINVISIBLEANNOTATIONS, RUNTIMEVISIBLEPARAMETERANNOTATIONS, RUNTIMEINVISIBLEPARAMETERANNOTATIONS, ANNOTATIONDEFAULT, BOOTSTRAPMETHODS
}